export enum KeyboardTypes {
  QWERTY = "qwerty",
  NUMBER = "number",
  QWERTY_NOT_CHARS = "qwerty_not_chars",
}

// export const inputFieldComp = [
//   InputTypes.STRING_LIST,
//   InputTypes.REPEATER_TABS,
//   InputTypes.SORTABLE_LIST,
//   InputTypes.COMBOBOX,
//   InputTypes.MULTI_SELECT,
//   InputTypes.REPEATER,
//   InputTypes.KEY_VALUE,
//   InputTypes.CURRENCY,
//   InputTypes.BUTTON_GROUP,
//   InputTypes.SLIDER,
//   InputTypes.FILE_MULTI_UPLOAD,
//   InputTypes.TIME,
//   InputTypes.DATE_TIME,
//   InputTypes.TAGS,
//   InputTypes.RADIO_GROUP,
//   InputTypes.TEXT_GROUP,
//   InputTypes.ACCORDION_GROUPED_SWITCH_LIST,
//   InputTypes.GROUPED_SWITCH_LIST,
//   InputTypes.TEXT,
//   InputTypes.SWITCH,
//   InputTypes.SIMPLE_CHECK_LIST,
//   InputTypes.CHECKBOX,
//   InputTypes.COLOR,
//   InputTypes.OTP,
//   InputTypes.SELECT,
//   InputTypes.DATE,
//   InputTypes.FILE,
//   InputTypes.FORM,
//   InputTypes.NUMBER,
//   InputTypes.TEXTAREA,
//   // InputTypes.SWITCH_LIST,
//   InputTypes.HIDDEN,
//   // ✨ New input types (v1.35.0)
//   InputTypes.RATING,
//   InputTypes.PHONE,
//   InputTypes.URL,
//   InputTypes.PASSWORD,
//   InputTypes.AUTOCOMPLETE,
//   // ✨ New input types (v1.36.0)
//   InputTypes.EMAIL,
//   InputTypes.SEARCH,
//   InputTypes.LOCATION_PICKER,
// ]