export enum InputTypes {
  HIDDEN = "hidden",
  TEXT = "text",
  TEXT_GROUP = "text_group",
  NUMBER = "number",
  SWITCH = "switch",
  CHECKBOX = "checkbox",
  SELECT = "select",
  SIMPLE_CHECK_LIST = "siple_checklist",
  CHECK_LIST = "checklist",
  // SWITCH_LIST = "switchlist",
  GROUPED_SWITCH_LIST = "grouped_switchlist",
  ACCORDION_GROUPED_SWITCH_LIST = "accordion_grouped_switchlist",
  DATE = "date",
  TEXTAREA = "textarea",
  FILE = "file",
  OTP = "otp",
  FORM = "form",
  COLOR = "color",
  RADIO_GROUP = "radio_group",
  TAGS = "tags",
  DATE_TIME = "date_time",
  TIME = "time",
  FILE_MULTI_UPLOAD = "file_multi_upload",
  SLIDER = "slider",
  BUTTON_GROUP = "button_group",
  CURRENCY = "currency",
  KEY_VALUE = "key_value",
  REPEATER = "repeater",
  MULTI_SELECT = "multi_select",
  COMBOBOX = "COMBO_BOX",
  SORTABLE_LIST = "sortable_list",
  REPEATER_TABS = "repeater_tabs",
  STRING_LIST = "string_list",
  
  // ✨ New input types (v1.35.0)
  RATING = "rating",
  PHONE = "phone",
  URL = "url",
  PASSWORD = "password",
  AUTOCOMPLETE = "autocomplete",
  
  // ✨ New input types (v1.36.0)
  EMAIL = "email",
  SEARCH = "search",
  LOCATION_PICKER = "location_picker",
  DATE_RANGE = "date_range",
  COUNTRY_SELECT = "country_select",
  RANGE = "range",
  
  // ✨ New input types (v1.37.0)
  FILE_UPLOAD = "file_upload",
}

export const inputFieldComp: InputTypes[] = [
  InputTypes.STRING_LIST,
  InputTypes.REPEATER_TABS,
  InputTypes.SORTABLE_LIST,
  InputTypes.COMBOBOX,
  InputTypes.MULTI_SELECT,
  InputTypes.REPEATER,
  InputTypes.KEY_VALUE,
  InputTypes.CURRENCY,
  InputTypes.BUTTON_GROUP,
  InputTypes.SLIDER,
  InputTypes.FILE_MULTI_UPLOAD,
  InputTypes.TIME,
  InputTypes.DATE_TIME,
  InputTypes.TAGS,
  InputTypes.RADIO_GROUP,
  InputTypes.TEXT_GROUP,
  InputTypes.ACCORDION_GROUPED_SWITCH_LIST,
  InputTypes.GROUPED_SWITCH_LIST,
  InputTypes.TEXT,
  InputTypes.SWITCH,
  InputTypes.SIMPLE_CHECK_LIST,
  InputTypes.CHECKBOX,
  InputTypes.COLOR,
  InputTypes.OTP,
  InputTypes.SELECT,
  InputTypes.DATE,
  InputTypes.FILE,
  InputTypes.FORM,
  InputTypes.NUMBER,
  InputTypes.TEXTAREA,
  // InputTypes.SWITCH_LIST,
  InputTypes.HIDDEN,
  // ✨ New input types (v1.35.0)
  InputTypes.RATING,
  InputTypes.PHONE,
  InputTypes.URL,
  InputTypes.PASSWORD,
  InputTypes.AUTOCOMPLETE,
  // ✨ New input types (v1.36.0)
  InputTypes.EMAIL,
  InputTypes.SEARCH,
  InputTypes.LOCATION_PICKER,
  InputTypes.DATE_RANGE,
  InputTypes.COUNTRY_SELECT,
  InputTypes.RANGE,
  // ✨ New input types (v1.37.0)
  InputTypes.FILE_UPLOAD,
]